// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LogInSuccess(arg1) {
  return window['go']['main']['App']['LogInSuccess'](arg1);
}

export function SwitchAccountSuccess() {
  return window['go']['main']['App']['SwitchAccountSuccess']();
}
